<a href="https://colab.research.google.com/github/neohack22/IASD/blob/reinforcement/prerequisites/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
mylist = [1,2,3]

In [ ]:
type(mylist)

list

In [ ]:
np.array(mylist)

array([1, 2, 3])

In [ ]:
mylist

[1, 2, 3]

In [ ]:
myarr = np.array(mylist)

In [ ]:
myarr

array([1, 2, 3])

In [ ]:
type(myarr)

numpy.ndarray

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [ ]:
len(np.linspace(0,5,21))

21

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(1)

array([0.18086681])

In [ ]:
np.random.rand(1)

array([0.9192256])

In [ ]:
np.random.rand(5,6)

array([[0.36030848, 0.86022673, 0.48563974, 0.83799146, 0.37578621,
        0.17979865],
       [0.30481331, 0.67895411, 0.94497761, 0.12347937, 0.20829014,
        0.3632397 ],
       [0.9864916 , 0.60388651, 0.39527382, 0.20607559, 0.12484408,
        0.03098801],
       [0.41973141, 0.81687505, 0.00831889, 0.94678221, 0.05590914,
        0.90457674],
       [0.52023672, 0.62411777, 0.11228841, 0.99492758, 0.54529515,
        0.02508183]])

In [ ]:
np.random.randn(10)

array([-0.35578913,  0.72323331,  0.08998777,  0.48135402, -0.17022358,
        0.15874892, -1.35388941, -0.73801216,  0.83100738,  0.6150631 ])

In [ ]:
np.random.randn(2,3)

array([[-0.0196726 ,  0.05309527, -0.60024034],
       [-0.34210363,  1.21306955,  0.48319528]])

In [ ]:
np.random.randint(0,101,5)

array([51, 43, 72,  9, 55])

In [ ]:
np.random.randint(0,101,(4,5)) #(0,101,(4,5))

array([[13, 87, 83, 90, 11],
       [84, 98, 34, 65, 98],
       [50, 90, 59, 43, 57],
       [ 2,  8, 84, 11, 85]])

In [ ]:
np.random.randint(0,101,10) #.randint(0,101,10)

array([73, 85, 89, 42, 99,  0, 16,  3,  7, 74])

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [ ]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [ ]:
arr = np.arange(0,25) #range(0,25)

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(5,4)

ValueError: ignored

In [ ]:
ranarr = np.random.randint(0,101,10)

In [ ]:
ranarr

array([ 9, 77, 40,  4, 63, 40, 60, 92, 64,  5])

In [ ]:
ranarr.max()

92

In [ ]:
ranarr.min()

4

In [ ]:
ranarr.argmax()

7

In [ ]:
ranarr.argmin()

3

In [ ]:
ranarr.dtype

dtype('int64')

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.shape

(25,)

In [ ]:
arr = arr.reshape(5,5)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.shape

(5, 5)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(1,25) #zpe(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

# Indexing and selection

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[0:5] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)

In [ ]:
slice_of_arr = arr[0:5]

In [ ]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr[:] = 99

In [ ]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy[:] = 100

In [ ]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_2d = np.array(
    [[#]
        5,10,15
    ],[
        20,25,30
    ],[
        35,40,45
    ]]
)

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d.shape

(3, 3)

In [ ]:
arr_2d[2]

array([35, 40, 45])

In [ ]:
arr_2d[0,2]

15

In [ ]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr = np.arange(1,11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

# Arithmetic Operations

In [ ]:
arr = np.arange(0,10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1 / 0

ZeroDivisionError: ignored

In [ ]:
1 / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.sum()

45

In [ ]:
arr.mean()

4.5

In [ ]:
arr.max()

9

In [ ]:
arr.var()

8.25

In [ ]:
arr.std()

2.8722813232690143

In [ ]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2d = np.arange(0,25).reshape(5,5)

In [ ]:
arr2d.shape

(5, 5)

In [ ]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2d.sum()

300

In [ ]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [ ]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

# Exercises

In [ ]:
import numpy as np

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(1)

array([0.0756819])

In [ ]:
np.random.randn(25)

array([ 0.91035914,  2.39810814,  1.43125938,  0.42334746,  0.06208316,
        0.2658639 , -0.09519518,  0.63311363, -0.21413838,  1.43666095,
       -0.28511481,  0.26328773,  1.51080327,  1.69877827, -0.39682137,
       -2.89835198,  0.76999556,  0.546213  ,  1.16893157,  0.98804578,
        0.98761444,  0.44744034,  1.08801834, -0.60188586, -0.27522432])

In [ ]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
arr = np.arange(1,101)/100
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat[3,4]

20

In [ ]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
mat[:3,1]

array([ 2,  7, 12])

In [ ]:
mat[:3,1:2] #,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [ ]:
mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat.sum()

325

In [ ]:
mat.std()

7.211102550927978

In [ ]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
np.random.seed(101)
np.random.rand(1)

array([0.51639863])