<a href="https://colab.research.google.com/github/neohack22/IASD/blob/prerequisites/TF/Crash_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
from sklearn.preprocessing import MinMaxScaler #b.preprocessing import MinMaxScaler

In [5]:
data  = np.random.randint(0,100,(10,2)) #int(0,100,(10,2))

In [6]:
data

array([[72, 53],
       [50, 92],
       [73, 70],
       [34, 38],
       [ 4, 93],
       [83, 90],
       [48, 43],
       [13, 88],
       [68, 23],
       [28, 73]])

In [7]:
scaler_model = MinMaxScaler()

In [8]:
type(scaler_model)

sklearn.preprocessing._data.MinMaxScaler

In [9]:
scaler_model.fit(data)

MinMaxScaler()

In [10]:
scaler_model.transform(data)

array([[0.86075949, 0.42857143],
       [0.58227848, 0.98571429],
       [0.87341772, 0.67142857],
       [0.37974684, 0.21428571],
       [0.        , 1.        ],
       [1.        , 0.95714286],
       [0.55696203, 0.28571429],
       [0.11392405, 0.92857143],
       [0.81012658, 0.        ],
       [0.30379747, 0.71428571]])

In [12]:
scaler_model.fit_transform(data)

array([[0.86075949, 0.42857143],
       [0.58227848, 0.98571429],
       [0.87341772, 0.67142857],
       [0.37974684, 0.21428571],
       [0.        , 1.        ],
       [1.        , 0.95714286],
       [0.55696203, 0.28571429],
       [0.11392405, 0.92857143],
       [0.81012658, 0.        ],
       [0.30379747, 0.71428571]])

In [13]:
import pandas as pd

In [15]:
mydata=np.random.randint(0,101,(50,4))

In [16]:
mydata

array([[ 65,  70,  58,  68],
       [ 57,  87,  61,  14],
       [ 18,  70,  26,  14],
       [ 80,  25,  25,  63],
       [ 21,  27,  84,  50],
       [ 75,  11,  37,  45],
       [ 26,  75,  69,  59],
       [ 45,  27,  75,  90],
       [100,   6,  86,  68],
       [ 68,  89,  47,  11],
       [ 11,   3,  82,  47],
       [ 18,  24,  70,  45],
       [ 85,  61,  45,  57],
       [  7,  26,  29,  82],
       [ 97,  26,  54,  47],
       [ 84,  49,  27,  21],
       [ 19,  10,  15,  94],
       [ 19,  45,  85,  71],
       [100,  51,  13,  93],
       [ 65,  35,  23,  21],
       [  7,  80, 100,  91],
       [ 57,  24,  74,  94],
       [ 22,   7,  45,  64],
       [ 66,  71,  39,  53],
       [ 26,  93,  30,  73],
       [ 34,   8,  78,  12],
       [  2,  59,  39,  62],
       [  2,  88,  64,  14],
       [ 94,  21,  77,  88],
       [ 98,  34,  15,  66],
       [ 27,  58,  45,  90],
       [ 70,  92,  24,  93],
       [ 37,  82,  15,  21],
       [ 80,  54,  49,  37],
       [ 62,  

In [20]:
df = pd.DataFrame(data=mydata, columns = ['f1', 'f2', 'f3', 'label'])

In [21]:
df

f1  f2   f3  label
0    65  70   58     68
1    57  87   61     14
2    18  70   26     14
3    80  25   25     63
4    21  27   84     50
5    75  11   37     45
6    26  75   69     59
7    45  27   75     90
8   100   6   86     68
9    68  89   47     11
10   11   3   82     47
11   18  24   70     45
12   85  61   45     57
13    7  26   29     82
14   97  26   54     47
15   84  49   27     21
16   19  10   15     94
17   19  45   85     71
18  100  51   13     93
19   65  35   23     21
20    7  80  100     91
21   57  24   74     94
22   22   7   45     64
23   66  71   39     53
24   26  93   30     73
25   34   8   78     12
26    2  59   39     62
27    2  88   64     14
28   94  21   77     88
29   98  34   15     66
30   27  58   45     90
31   70  92   24     93
32   37  82   15     21
33   80  54   49     37
34   62  30   44     12
35   57  30   43    100
36   36  50   48     63
37   34   3   99     98
38   74  14    1     71
39    5  54   25     79
40   80  52   42      6
41   11  55    1      9
42   38  16   44     94
43   69  26   93     58
44   80  62   43     62
45   61  44   62     46
46    9  97   27     49
47   82  69   63      6
48   36  43   13     35
49   26  38   33      1

In [22]:
X = df[['f1', 'f2', 'f3']]

In [23]:
y = df['label']

In [24]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y__train, y_test = train_test_split( #T_test, y_train, y_test = train_test_split( #est = train_test_split(
        X, y, test_size=0.3, random_state=101) #)

In [28]:
X_train.shape

(35, 3)

In [31]:
X_test.shape

(15, 3)